# Generated by Django 4.2.16 on 2026-01-22 14:43

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def copy_operadores(apps, schema_editor):
    RegistroTurno = apps.get_model('horas_extras', 'RegistroTurno')
    ResumenMensual = apps.get_model('horas_extras', 'ResumenMensual')
    Empleado = apps.get_model('horas_extras', 'Empleado')
    Role = apps.get_model('user_management', 'Role')
    UserRole = apps.get_model('user_management', 'UserRole')

    user_app_label, user_model_name = settings.AUTH_USER_MODEL.split('.')
    UserModel = apps.get_model(user_app_label, user_model_name)

    rol_operador, _ = Role.objects.get_or_create(
        name='operador de centro de computo',
        defaults={
            'description': 'Operador de centro de computo - Gestiona turnos y monitoreo',
            'puede_ver_reportes': True,
            'puede_monitorear_servidores': True,
            'activo': True,
        },
    )

    def asegurar_usuario(empleado):
        if empleado.user_id:
            return empleado.user_id

        base = empleado.numero_empleado or empleado.cedula or str(empleado.pk)
        base = base.replace(' ', '_').lower()
        username_base = f"emp_{base}"
        username = username_base
        consecutivo = 1
        while UserModel.objects.filter(username=username).exists():
            username = f"{username_base}_{consecutivo}"
            consecutivo += 1

        email = f"{username}@sacsbd.local"
        user = UserModel.objects.create_user(
            username=username,
            email=email,
            password='TempPassword123!'
        )

        empleado.user_id = user.pk
        empleado.save(update_fields=['user'])
        return user.pk

    empleado_a_usuario = {}
    for empleado in Empleado.objects.all().only('pk', 'user_id', 'numero_empleado', 'cedula'):
        user_id = asegurar_usuario(empleado)
        empleado_a_usuario[empleado.pk] = user_id
        UserRole.objects.get_or_create(
            user_id=user_id,
            role=rol_operador,
            defaults={'activo': True}
        )

    for turno in RegistroTurno.objects.all().only('pk', 'empleado_id'):
        if turno.empleado_id is None:
            continue
        turno.operador_id = empleado_a_usuario.get(turno.empleado_id)
        turno.save(update_fields=['operador'])

    for resumen in ResumenMensual.objects.all().only('pk', 'empleado_id'):
        if resumen.empleado_id is None:
            continue
        resumen.operador_id = empleado_a_usuario.get(resumen.empleado_id)
        resumen.save(update_fields=['operador'])


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('horas_extras', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registroturno',
            options={'ordering': ['-fecha', 'operador'], 'verbose_name': 'Registro de Turno', 'verbose_name_plural': 'Registros de Turno'},
        ),
        migrations.AlterModelOptions(
            name='resumenmensual',
            options={'ordering': ['-ano', '-mes'], 'verbose_name': 'Resumen Mensual', 'verbose_name_plural': 'Resúmenes Mensuales'},
        ),
        migrations.AlterUniqueTogether(
            name='registroturno',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='resumenmensual',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='registroturno',
            name='operador',
            field=models.ForeignKey(blank=True, help_text='Usuario con rol de operador de centro de computo', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='turnos', to=settings.AUTH_USER_MODEL, verbose_name='Operador'),
        ),
        migrations.AddField(
            model_name='resumenmensual',
            name='fecha_calculo',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='resumenmensual',
            name='horas_dominicales',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6),
        ),
        migrations.AddField(
            model_name='resumenmensual',
            name='horas_nocturnas',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6),
        ),
        migrations.AddField(
            model_name='resumenmensual',
            name='horas_nocturnas_festivas',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6),
        ),
        migrations.AddField(
            model_name='resumenmensual',
            name='operador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resumenes_turnos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(copy_operadores, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='tipoturno',
            name='codigo',
            field=models.CharField(help_text='Código del turno (ej: Apoyo-A, Turno 1-M, etc.)', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='tipoturno',
            name='es_nocturno',
            field=models.BooleanField(default=False, help_text='Turno que incluye horario nocturno'),
        ),
        migrations.AlterUniqueTogether(
            name='registroturno',
            unique_together={('operador', 'fecha')},
        ),
        migrations.AlterUniqueTogether(
            name='resumenmensual',
            unique_together={('operador', 'mes', 'ano')},
        ),
        migrations.DeleteModel(
            name='CalculoRecargo',
        ),
        migrations.RemoveField(
            model_name='registroturno',
            name='empleado',
        ),
        migrations.RemoveField(
            model_name='registroturno',
            name='horas_extras',
        ),
        migrations.RemoveField(
            model_name='resumenmensual',
            name='actualizado_en',
        ),
        migrations.RemoveField(
            model_name='resumenmensual',
            name='empleado',
        ),
        migrations.RemoveField(
            model_name='resumenmensual',
            name='fecha_generacion',
        ),
        migrations.RemoveField(
            model_name='resumenmensual',
            name='total_a_pagar',
        ),
        migrations.RemoveField(
            model_name='resumenmensual',
            name='total_horas_extras',
        ),
        migrations.RemoveField(
            model_name='resumenmensual',
            name='total_recargos_dominicales',
        ),
        migrations.RemoveField(
            model_name='resumenmensual',
            name='total_recargos_festivos',
        ),
        migrations.RemoveField(
            model_name='resumenmensual',
            name='total_recargos_nocturno_festivo',
        ),
        migrations.RemoveField(
            model_name='resumenmensual',
            name='total_recargos_nocturnos',
        ),
        migrations.RemoveField(
            model_name='resumenmensual',
            name='total_valor_horas_extras',
        ),
        migrations.RemoveField(
            model_name='resumenmensual',
            name='total_valor_ordinario',
        ),
        migrations.RemoveField(
            model_name='resumenmensual',
            name='total_valor_recargos',
        ),
        migrations.AlterField(
            model_name='registroturno',
            name='operador',
            field=models.ForeignKey(help_text='Usuario con rol de operador de centro de computo', on_delete=django.db.models.deletion.CASCADE, related_name='turnos', to=settings.AUTH_USER_MODEL, verbose_name='Operador'),
        ),
        migrations.AlterField(
            model_name='resumenmensual',
            name='operador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resumenes_turnos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Empleado',
        ),
    ]
