# Generated by Django 4.2.16 on 2026-01-26 05:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('horas_extras', '0002_remove_empleado_user_alter_registroturno_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatronOperador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio_patron', models.DateField(help_text='Fecha ancla donde el operador tenía el turno especificado')),
                ('turno_inicial_patron', models.CharField(choices=[('T', 'Tarde'), ('N', 'Noche'), ('D', 'Descanso'), ('M', 'Mañana')], help_text='Turno que el operador tenía en la fecha_inicio_patron', max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('operador', models.OneToOneField(help_text='Operador al que pertenece este patrón', on_delete=django.db.models.deletion.CASCADE, related_name='patron_turno', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Patrón de Operador',
                'verbose_name_plural': 'Patrones de Operadores',
            },
        ),
    ]
