# Generated by Django 4.2.16 on 2026-01-26 08:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('horas_extras', '0003_patronoperador'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patronoperador',
            options={'ordering': ['-fecha_inicio_patron'], 'verbose_name': 'Patrón de Operador', 'verbose_name_plural': 'Patrones de Operadores'},
        ),
        migrations.AddField(
            model_name='patronoperador',
            name='motivo',
            field=models.CharField(blank=True, default='', help_text='Motivo del cambio (vacaciones, reubicación, etc.)', max_length=100),
        ),
        migrations.AlterField(
            model_name='patronoperador',
            name='fecha_inicio_patron',
            field=models.DateField(help_text='Fecha donde comienza a aplicarse este patrón'),
        ),
        migrations.AlterField(
            model_name='patronoperador',
            name='operador',
            field=models.ForeignKey(help_text='Operador al que pertenece este patrón', on_delete=django.db.models.deletion.CASCADE, related_name='patrones_turno', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='patronoperador',
            name='turno_inicial_patron',
            field=models.CharField(choices=[('T', 'Tarde'), ('N', 'Noche'), ('D', 'Descanso'), ('M', 'Mañana')], help_text='Turno que el operador tiene en fecha_inicio_patron', max_length=1),
        ),
        migrations.AlterUniqueTogether(
            name='patronoperador',
            unique_together={('operador', 'fecha_inicio_patron')},
        ),
    ]
