# Generated by Django 5.2.9 on 2026-01-27 01:57

import datetime
import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horas_extras', '0004_alter_patronoperador_options_patronoperador_motivo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParametroNormativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vigencia_desde', models.DateField(help_text='Fecha desde la cual aplican estos parámetros', unique=True)),
                ('vigencia_hasta', models.DateField(blank=True, help_text='Fecha hasta la cual aplican (null = vigente indefinidamente)', null=True)),
                ('hora_inicio_nocturno', models.TimeField(default=datetime.time(21, 0), help_text='Hora inicio jornada nocturna (Art. 160 CST)')),
                ('hora_fin_nocturno', models.TimeField(default=datetime.time(6, 0), help_text='Hora fin jornada nocturna')),
                ('recargo_nocturno', models.DecimalField(decimal_places=2, default=Decimal('0.35'), help_text='Recargo nocturno ordinario (35% = 0.35)', max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('recargo_dominical_festivo', models.DecimalField(decimal_places=2, default=Decimal('0.75'), help_text='Recargo dominical/festivo diurno (75% = 0.75)', max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('recargo_nocturno_festivo', models.DecimalField(decimal_places=2, default=Decimal('1.10'), help_text='Recargo nocturno en festivo (35% + 75% = 1.10)', max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('recargo_extra_diurno', models.DecimalField(decimal_places=2, default=Decimal('0.25'), help_text='Hora extra diurna (25%)', max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('recargo_extra_nocturno', models.DecimalField(decimal_places=2, default=Decimal('0.75'), help_text='Hora extra nocturna (75%)', max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('jornada_diaria_max', models.IntegerField(default=8, help_text='Máximo de horas ordinarias por día', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('jornada_semanal_max', models.IntegerField(default=44, help_text='Máximo de horas ordinarias por semana (2025: 44h)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(60)])),
                ('divisor_mensual', models.IntegerField(default=220, help_text='Divisor para cálculo de valor hora (2025: 220)')),
                ('tope_extra_dia', models.IntegerField(default=2, help_text='Máximo de horas extra autorizadas por día')),
                ('tope_extra_semana', models.IntegerField(default=12, help_text='Máximo de horas extra autorizadas por semana')),
                ('descripcion', models.TextField(blank=True, help_text='Descripción de esta versión de parámetros (ej: "Ley 2101 - Reforma 2025")')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Parámetro Normativo',
                'verbose_name_plural': 'Parámetros Normativos',
                'ordering': ['-vigencia_desde'],
            },
        ),
        migrations.CreateModel(
            name='PoliticaEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vigencia_desde', models.DateField(help_text='Fecha desde la cual aplica esta política', unique=True)),
                ('pagar_dominical_100', models.BooleanField(default=False, help_text='Si True, paga dominicales al 100% en lugar del 75% legal')),
                ('sabado_es_descanso', models.BooleanField(default=False, help_text='Si True, sábado se considera día de descanso (recargo adicional)')),
                ('redondear_minutos', models.IntegerField(default=0, help_text='Redondear minutos al múltiplo indicado (0 = no redondear)')),
                ('usar_banco_horas', models.BooleanField(default=False, help_text='Si True, habilita compensación de tiempo en lugar de pago')),
                ('descripcion', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Política de Empresa',
                'verbose_name_plural': 'Políticas de Empresa',
                'ordering': ['-vigencia_desde'],
            },
        ),
        migrations.AlterField(
            model_name='patronoperador',
            name='turno_inicial_patron',
            field=models.CharField(choices=[('T', 'Tarde'), ('N', 'Noche'), ('D', 'Descanso'), ('M', 'Mañana'), ('A', 'Apoyo')], help_text='Turno que el operador tiene en fecha_inicio_patron', max_length=1),
        ),
    ]
