# Generated by Django 4.2.16 on 2026-01-28 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horas_extras', '0005_add_motor_normativo'),
    ]

    operations = [
        migrations.AddField(
            model_name='patronoperador',
            name='es_solo_referencia',
            field=models.BooleanField(default=True, help_text='Este patrón solo se usa como referencia visual, NO genera turnos automáticamente'),
        ),
    ]
