# Generated by Django 5.2.9 on 2026-01-29 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horas_extras', '0006_patronoperador_es_solo_referencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipoturno',
            name='nombre',
            field=models.CharField(choices=[('manana', 'Turno Mañana'), ('tarde', 'Turno Tarde'), ('noche', 'Turno Noche'), ('noche_w1', 'Noche Miércoles 1h'), ('noche_w2', 'Noche Miércoles 6h'), ('apoyo', 'Turno Apoyo'), ('descanso', 'Día Descanso')], max_length=20, unique=True),
        ),
    ]
