# Generated by Django 5.2.9 on 2026-01-30 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horas_extras', '0007_alter_tipoturno_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametronormativo',
            name='configuracion_turnos',
            field=models.TextField(blank=True, default='{}', help_text="JSON para sobrescribir horarios. Ej: {'M': {'semana': ['06:00', '13:00']}}"),
        ),
    ]
