# Generated by Django 4.2.16 on 2025-10-31 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='metadata',
            field=models.TextField(blank=True),
        ),
    ]
